# Generated by Django 4.2.2 on 2023-06-29 02:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0002_default_recommandation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre_data',
            name='genre',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='record',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=2990), blank=True, size=None),
        ),
        migrations.AlterField(
            model_name='view_record',
            name='record',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9990), blank=True, size=None),
        ),
    ]
