# Generated by Django 4.2.2 on 2023-06-29 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommandation', '0003_alter_genre_data_genre_alter_recommandation_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre_data',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recommandation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='view_record',
            name='id',
        ),
        migrations.AlterField(
            model_name='genre_data',
            name='movie_id',
            field=models.CharField(max_length=9999, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recommandation',
            name='account_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommandation.view_record'),
        ),
        migrations.AlterField(
            model_name='view_record',
            name='account_id',
            field=models.CharField(max_length=9999, primary_key=True, serialize=False),
        ),
    ]
